version: "3.7"
services:
    www:
        image: php:8.0.2-apache
        ports:
            - "80:80"
        volumes:
            - ./src:/var/www/html/
        networks:
            - default
        depends_on:
            - db
        command: "/bin/sh -c 'docker-php-ext-install mysqli && exec docker-php-entrypoint apache2-foreground'"
        deploy:
            mode: replicated
            replicas: 3
            placement:
                constraints: [node.role == manager]
            restart_policy:
                condition: on-failure

    db:
        image: mysql:latest
        environment:
            MYSQL_DATABASE: db
            MYSQL_ROOT_PASSWORD: root
            MYSQL_USER: user
            MYSQL_PASSWORD: password
        command: --secure_file_priv=""
        ports:
            - "3306:3306"
        restart: always
        volumes:
            - ./dataset:/data
            - ./schema.sql:/docker-entrypoint-initdb.d/1_schema.sql
            - ./data.sql:/docker-entrypoint-initdb.d/2_data.sql
        cap_add:
            - SYS_NICE
        deploy:
            placement:
                constraints: [node.role == manager]

    app:
        depends_on:
         - db
        image: phpmyadmin/phpmyadmin
        restart: always
        ports:
            - '5000:80'
        environment:
            PMA_HOST: db