version: "3.7"
services:
    www:
        build: .
        ports:
            - "80:80"
        volumes:
            - ./src:/var/www/html/
        networks:
            - default
        depends_on:
            - db

    db:
        image: mysql:latest
        environment:
            MYSQL_ROOT_PASSWORD: root
        ports:
            - "3306:3306"
        volumes:
            - ./dataset:/data